{% raw %}
name: Build and upload extension

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel toml cython
      - name: Build extension
        run: |
          VERSION=${{ github.event.release.tag_name }} python setup.py bdist_wheel
      - name: Check for leaking source code
        run: |
          ! (unzip -Z1 dist/*.whl | grep ".py$")
          ! (unzip -Z1 dist/*.whl | grep ".c$")
      - name: Upload extension to store
        uses: nicoconsultancy/publish-imm-extension@v2
        with:
          access_token: ${{ secrets.IMM_STORE_TOKEN }}
{% endraw %}