{% raw %}---
name: Semantic Release

# This job runs semantic-release on every push to master. If there is a fix: or feat: commit, then semantic-release
# will create a GitHub release for this version. It'll also commit the CHANGELOG.md back to the repo.
# The GitHub release will trigger the build.yml workflow that builds the .whl and uploads it to the store.

on:
  push:
    branches: [master, main]


jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git

      - name: Release
        run: npx semantic-release
        env:
          IMM_STORE_TOKEN: ${{ secrets.IMM_STORE_TOKEN }}
          IMM_STORE_URL: ${{ secrets.IMM_STORE_URL }}
          GIT_AUTHOR_NAME: ${{ secrets.IMM_BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.IMM_BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.IMM_BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.IMM_BOT_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.IMM_BOT_TOKEN }}
{% endraw %}
