exclude: '^$'
default_language_version:
    python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast  # check .py files are valid
      - id: check-case-conflict
      - id: check-yaml  # Attempts to load all yaml files to verify syntax
      - id: check-json  # Attempts to load all json files to verify syntax
      - id: check-toml  # Attempts to load all toml files to verify syntax
      - id: check-xml  # Attempts to load all xml files to verify syntax
      - id: check-merge-conflict  # Check for files that contain merge conflict strings
      - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline
      - id: trailing-whitespace
      - id: debug-statements  # Check for debugger imports and py37+ breakpoint() calls in python source
      - id: name-tests-test  # Assert that files in tests/ end in _test.py
        exclude: tests/fixtures
      - id: detect-private-key  # Check that nothing that looks like a private key was commited
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
      - id: python-check-blanket-noqa  # Enforce that noqa annotations always occur with specific codes
      - id: python-no-eval  # A quick check for the eval() built-in function
      - id: python-no-log-warn  # A quick check for the deprecated .warn() method of python loggers
      - id: python-use-type-annotations  # Enforce that python3.6+ type annotations are used instead of type comments
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['--in-place', '--imports=django,requests,rest_framework,imm', '--remove-duplicate-keys']
  - repo: https://github.com/asottile/yesqa
    rev: v1.2.2
    hooks:
      - id: yesqa
        additional_dependencies: [
          'flake8-builtins',
          'flake8-comprehensions',
          'flake8-django',
          'flake8-pytest-style',
          'flake8-print',
          'flake8-return',
          'flake8-bugbear',
          'flake8-sfs',
          'flake8-super',
          'flake8-tidy-imports',
          'pep8-naming',
          'flake8-mutable',
        ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-builtins',
          'flake8-comprehensions',
          'flake8-django',
          'flake8-pytest-style',
          'flake8-print',
          'flake8-bugbear',
          'flake8-return',
          'flake8-sfs',
          'flake8-super',
          'flake8-tidy-imports',
          'pep8-naming',
          'flake8-mutable',
        ]
